In [1]:
import pandas as pd
import numpy as np
#Import full data set using Pandas:
data=pd.read_csv('/Users/yangxiang/A List/Uchicago/2020_Spring/NLP/Week_1/Food_Inspections.csv')
data.shape

(204389, 17)

In [2]:
data

Inspection ID                                     DBA Name  \
0             2185053                    NEW HONG KONG BUFFET, INC   
1             2365877                         STEVE'S 77 ICE CREAM   
2             2365636                             Morgan Park(H/S)   
3             2185115                                    SIMPLY IT   
4             2222745                                   MY BUDDY'S   
5             2367144               Chicago Prep Master Tenant LLC   
6              580885                          CESAR'S ON BROADWAY   
7             2200230                      TAHOORA SWEETS & BAKERY   
8             1584185                            THE FIREPLACE INN   
9             1527833                        CARRIBEAN JERK PALACE   
10            2366699                          HAIRE'S GULF SHRIMP   
11            2362267                              BISI RESTAURANT   
12            2185036                           MINI PALAPITA INC.   
13            2311756               GATEWAY FOUNDATION-KEDZIE CENT   
14            2213602                     LA MIXTECA POBLANA 2 LLC   
15            1106321                          KHAN BBQ RESTAURANT   
16            2301117                          MANOLO'S TAMALES #3   
17            2261818                                         BITE   
18            1567108                      SUPERMERCADO LA TAPATIA   
19            1515954                              MARIANO'S #8516   
20            2312526                              MARIANO'S #8522   
21            2312847                              SUBWAY SANDWICH   
22            2304473                      EL RANCHITO FOOD MARKET   
23            2311600                          DOLLAR INN PLUS INC   
24            2213494  HACIENDA LA AMISTAD RESTAURANT, CORPORATION   
25            2312223                             ZIA'S LAGO VISTA   
26            2304884                           SERENA  RESTAURANT   
27            2213775                        TREASURE ISLAND FOODS   
28            1230079             MAMA LUCY'S CATERING CORPORATION   
29            1533151                           JOE'S BARBQUE, INC   
...               ...                                          ...   
204359        1360838             EL GLOBO BAKERY & ICE CREAM,INC.   
204360        1285831                           PICOSITO GRILL-BAR   
204361        1198818                         BUTCHER & THE BURGER   
204362        1383462                  SWISSOTEL - CONCOURSE LEVEL   
204363         391353                  INSPIRATION KITCHENS UPTOWN   
204364        1386501                           ARAMARK FOOD COURT   
204365         581128                 PARK PACKING OF CHICAGO, INC   
204366        1609898                             Burger Hub, Inc.   
204367        1976346                         THE MECCA RESTAURANT   
204368        2150310                               STAR SUBMARINE   
204369        2169962                LOS MANGOS NEVERIA Y FRUTERIA   
204370        1325061                          PETE'S FRESH MARKET   
204371         531740                                SWEET STATION   
204372        2064598                  ILLINOIS SPORTSERVICE, INC.   
204373        2014212                       STARBUCKS COFFEE #2949   
204374         580798                      THAI VILLAGE RESTAURANT   
204375        2059335                                 BUEN APETITO   
204376        1467638                       EASTSIDE  MARATHON INC   
204377        1319780                          STANLEY'S ON RACINE   
204378        2279883                         REMEDY AT AON CENTER   
204379         565625                      STARBUCKS COFFEE #11719   
204380        2365679                                    Kozminski   
204381        2359601                       LA CASA DEL PAN BAKERY   
204382        1092601                 CHICAGO PIZZA & OVEN GRINDER   
204383        1151596                HILL OF ANGELS DAYCARE CENTER   
204384         537

#### multinomial classifier

In [309]:
# Choose 'Pass','Fail','Pass w/ Conditions' ,'Out of Business' from the Results Column as the responce variable
data = data[(data.Results =='Pass') | (data.Results =='Fail') | (data.Results =='Pass w/ Conditions')| (data.Results =='Out of Business')]

In [310]:
data['Results'].value_counts()

Pass                  108500
Fail                   39475
Pass w/ Conditions     29880
Out of Business        17656
Name: Results, dtype: int64

In [311]:
#Making sure that there are no NaNs in "Violations" column
data=data.dropna(subset=['Violations'])

#### Leverage the results of your homework from Week-1 and Week-2 to extract free-form text comments from inspectors
#### Discard the text from “Health Code” – only keep inspectors’ comments

In [312]:
#Using regular expression, parse "Violations" column to select only Comments, create a new column 'Comments'
data=data.reset_index(drop=True)
import re
data['Comments'] =data['Violations'].apply(lambda x: re.findall('Comments[A-Za-z\s\d\:\,\&\;\-\/\.\(\)\"\#\!\@\#\$\%\^\*\_\+\=\\\{\}\[\]\\\'\<\>\?\~\`]+', x))

In [313]:
#Change from list to string for the comment column
data['Comments'] =data['Comments'].apply(lambda x: ' '.join(x))

In [314]:
#Remove "Comments" string
data['Comments']=data['Comments'].apply(lambda x: [re.sub('Comments:','',x)])

In [315]:
#Remove all digital numbers(Remove Health Code)
data['Comments'] =data['Violations'].apply(lambda x: re.findall('\D+', x))

In [316]:
#Change from list to string for the comment column
data['Comments'] =data['Comments'].apply(lambda x: ' '.join(x))

#### Build classification model, predicting the outcome of inspection – your target variable is “Results”

In [317]:
# convert label to a binary numerical variable
data['Results_flag'] = data.Results.map({'Pass':0, 'Fail':1, 'Pass w/ Conditions':2, 'Out of Business':2})

In [318]:
# how to define X and y (from the citation data) for use with COUNTVECTORIZER
X = data.Comments
y = data.Results_flag
print(X.shape)
print(y.shape)

(149590,)
(149590,)


In [319]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1,test_size=0.2)

#### Vectorizing our dataset

I choose CountVectorizer as my text pre-processing technique.
CountVectorizer is able to Convert a collection of text documents to a matrix of token counts

In [338]:
# instantiate the vectorizer
from sklearn.feature_extraction.text import CountVectorizer, HashingVectorizer, TfidfTransformer, TfidfVectorizer
vect = CountVectorizer(stop_words='english',ngram_range=(1, 3),max_df=0.5,min_df=2)
#vect = HashingVectorizer(n_features=15)
#vect = TfidfVectorizer(stop_words='english',ngram_range=(1, 3),max_df=0.5,min_df=2)

In [339]:
# learn training data vocabulary, then use it to create a document-term matrix
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

In [340]:
# transform testing data (using fitted vocabulary) into a document-term matrix
X_test_dtm = vect.transform(X_test)
X_test_dtm

<29918x874424 sparse matrix of type '<class 'numpy.int64'>'
	with 7593343 stored elements in Compressed Sparse Row format>

##### Building and evaluating models

###### Naive Bayes Model

In [341]:
from sklearn.naive_bayes import MultinomialNB
# instantiate a Multinomial Naive Bayes model
nb = MultinomialNB()

In [342]:
# train and time the model using X_train_dtm
%time nb.fit(X_train_dtm, y_train)

CPU times: user 444 ms, sys: 40.5 ms, total: 484 ms
Wall time: 464 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [343]:
# make class predictions for X_test_dtm
y_pred_class = nb.predict(X_test_dtm)

In [344]:
# calculate accuracy of class predictions
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(accuracy_score(y_test, y_pred_class))

0.8696771174543753


In [345]:
# calculate precision and recall
print(classification_report(y_test, y_pred_class))

              precision    recall  f1-score   support

           0       0.97      0.94      0.95     16868
           1       0.81      0.79      0.80      7212
           2       0.70      0.78      0.74      5838

    accuracy                           0.87     29918
   macro avg       0.82      0.83      0.83     29918
weighted avg       0.87      0.87      0.87     29918



In [346]:
# calculate the confusion matrix
print(confusion_matrix(y_test, y_pred_class))

[[15787   235   846]
 [  402  5689  1121]
 [  168  1127  4543]]


In [347]:
# show default parameters for CountVectorizer
vect

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=0.5, max_features=None, min_df=2,
                ngram_range=(1, 3), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

###### Logistic Regression Model

In [350]:
# instantiate a logistic regression model
from sklearn.linear_model import LogisticRegression, SGDClassifier
logreg = LogisticRegression()

In [351]:
# train the model using X_train_dtm
%time logreg.fit(X_train_dtm, y_train)

CPU times: user 3min 10s, sys: 7.62 s, total: 3min 18s
Wall time: 2min 39s


/Users/yangxiang/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [352]:
# make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test_dtm)

In [354]:
# calculate accuracy of class predictions
print(accuracy_score(y_test, y_pred_class))

0.9463867905608664


In [355]:
# calculate precision and recall
print(classification_report(y_test, y_pred_class))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98     16868
           1       0.91      0.90      0.90      7212
           2       0.89      0.88      0.89      5838

    accuracy                           0.95     29918
   macro avg       0.93      0.92      0.93     29918
weighted avg       0.95      0.95      0.95     29918



In [357]:
# calculate the confusion matrix
print(confusion_matrix(y_test, y_pred_class))

[[16700    93    75]
 [  212  6458   542]
 [  146   536  5156]]


###### Support Vector Machine

In [358]:
# instantiate a SVM model
svm = SGDClassifier(max_iter=100, tol=None)

In [359]:
# train the model using X_train_dtm
%time svm.fit(X_train_dtm, y_train)

CPU times: user 58.5 s, sys: 1.41 s, total: 59.9 s
Wall time: 1min


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=100, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=None,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [360]:
# make class predictions for X_test_dtm
y_pred_class = svm.predict(X_test_dtm)

In [361]:
# calculate accuracy of class predictions
print(accuracy_score(y_test, y_pred_class))

0.9434119927802661


In [362]:
# calculate precision and recall
print(classification_report(y_test, y_pred_class))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98     16868
           1       0.92      0.89      0.90      7212
           2       0.90      0.88      0.89      5838

    accuracy                           0.94     29918
   macro avg       0.93      0.92      0.92     29918
weighted avg       0.94      0.94      0.94     29918



In [363]:
# calculate the confusion matrix
print(confusion_matrix(y_test, y_pred_class))

[[16673    98    97]
 [  310  6421   481]
 [  231   476  5131]]


 # Logistic Regression Model shows the highest accuracy rate 0.94638, so this is the best model for the analysis